appetizr/config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/"), categories for now, will be explore (restaurantes#index)
  root "restaurants#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :categories, param: :nombre
  
  resources :restaurants do
    post '/rank', to: 'ranks#create'
    resources :dishes, only: [:show, :new, :create, :edit, :update, :destroy]
  end

  get 'search', to: 'restaurants#search', as: 'search_restaurants'
  get '/restaurants/:id/stats', to: 'restaurants#stats'
  get '/restaurants/:id/edit_info', to: 'restaurants#edit_info'
  
  resources :posts, only: [:new, :create, :destroy] do
    get '/responses', to: 'post_responses#index' 
  end
  resources :reviews, only: [:new, :create, :destroy] do
    get '/responses', to: 'review_responses#index' 
  end
  
  get '/users/mis_restaurantes', to: 'users#mis_restaurantes'
  resources :users, param: :nombre
  post '/users/new', to: 'users#create'
  get '/is_rest_owner', to: 'users#is_restaurant_owner'
  
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout',  to: 'logins#destroy'

  resources :reactions, only: [:create, :update]
  resources :responses, only: [:new, :create, :destroy]
  
  get '/nearme', to: 'nearme#index', as: 'nearme'


  # Error pages
  get '/404', to: 'errors#not_found', via: :all
  get '/500', to: 'errors#internal_server_error', via: :all

  
  # /admin tiene que renderizar la vista admin/dashboard.html.erb
  get '/admin', to: 'admin#dashboard', as: 'admin_dashboard'
  get '/admin/promote', to: 'admin#promote', as: 'admin_promote'
  namespace :admin do
    get 'actualizar_datos', to: 'admin#actualizar_datos'
  end




  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  
  # root "posts#index"
  match '*unmatched', to: 'errors#not_found', via: :all
end

appetizr/app/models/user.rb
class User < ApplicationRecord
  self.primary_key = "nombre"

  has_many :posts, class_name: 'Post', foreign_key: 'autor', dependent: :destroy
  has_many :responses, class_name: 'Response', foreign_key: 'autor', dependent: :destroy
  has_many :reviews, class_name: 'Review', foreign_key: 'autor', dependent: :destroy
  has_many :ranks, class_name: 'Rank', foreign_key: 'who', dependent: :delete_all
  has_many :reactions, class_name: 'Reaction', foreign_key: 'who', dependent: :delete_all
  has_and_belongs_to_many :restaurants
  has_secure_password 


  before_destroy do |ts|
    responses.destroy
    reactions.delete
  end
end

appetizr/app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def index
    end
    
    def new
        @user = User.new
    end

    def is_restaurant_owner
    end


    def create
      nombre_imagen = subir_imagen(params.require(:user)[:ruta_img_perfil])
      @user = User.new(nombre: params[:user][:nombre], password: params[:user][:password], ruta_img_perfil: nombre_imagen, esAdmin: false, password_confirmation: params[:user][:password_confirmation])

      if @user.save
        session[:username] = @user.nombre
        redirect_to is_rest_owner_path, notice: "Cuenta creada"
      else
        render :new, status: unprocessable_entity
      end
    end

    def show
        @user = User.find_by(nombre: session[:username])
        # Numero de posts que ha hecho
        @num_posts = Post.where(autor: @user.id).count
        
        # Numero de platos y restaurantes sobre los que ha comentado
        @num_reviews = Review.where(autor: @user.id).count
        
        # Numero de respuestas que ha hecho
        @num_responses = Response.where(autor: @user.id).count

        # Numero de comentarios totales en el último mes
        @num_comments_last_month = 
          Post.where(autor: @user.id).where("created_at > ?", 1.month.ago).count +
          Review.where(autor: @user.id).where("created_at > ?", 1.month.ago).count + 
          Response.where(autor: @user.id).where("created_at > ?", 1.month.ago).count

        # Si el usuario es propietario de restaurantes, se calculan las estadísticas de sus restaurantes
        @num_restaurants_user = @user.restaurants.count

        @num_reviews_restaurant_last_month = 0
        @num_reviews_dishes_last_month = 0
        @num_responses_restaurant_last_month = 0
        @num_likes_restaurant_last_month = 0
        @num_dislikes_restaurant_last_month = 0
        
        if @num_restaurants_user > 0
          @user.restaurants.each do |restaurant|
            @num_reviews_restaurant_last_month += Review.where(reviewable_id: restaurant.id, reviewable_type: 'Restaurant').where("created_at > ?", 1.month.ago).count
            # MODIFICAR: reviewable_id tiene que ser un plato de restaurant
            restaurant.dishes.each do |dish|
              @num_reviews_dishes_last_month += Review.where(reviewable_id: dish.id, reviewable_type: 'Dish').where("created_at > ?", 1.month.ago).count
            end
            @num_likes_restaurant_last_month += Reaction.where(who: restaurant.id).where(reaccion: 'Like').count
            @num_dislikes_restaurant_last_month += Reaction.where(who: restaurant.id).where(reaccion: 'Dislike').count
          end
        end
    end

    def update
      @user = User.find_by(nombre: session[:username])
      nombre_imagen = subir_imagen(params.require(:user)[:ruta_img_perfil])
      
      if !@user.update(user_params.merge(ruta_img_perfil: nombre_imagen))
        render :edit, status: unprocessable_entity
      else 
        redirect_to user_path(@user.nombre), notice: "Perfil actualizado"
      end
    end

    def destroy
      @user = User.find_by(nombre: params[:nombre])
      if @user.destroy
        flash[:notice] = "Usuario eliminado"
      else
        flash[:notice] = "El usuario no ha podido ser eliminado"
      end
      redirect_to request.referer
    end
    
    def mis_restaurantes
      @user = User.find_by(nombre: session[:username])
      @restaurants = @user.restaurants
      
      render :mis_restaurantes
    end

    private
    def user_params
        params.require(:user).permit(:nombre, :password, :password_confirmation, :ruta_img_perfil)
    end
end

appetizr/app/helpers/users_helper.rb
module UsersHelper
end

appetizr/app/views/users/is_restaurant_owner.html.erb
<div class="log_in_container">
  <h1 class="log_in_title">¿Eres propietario de algún restaurante?</h1>
  <%= link_to 'Sí', new_restaurant_path, class: "register_button" %>
  <%= link_to 'No', root_path, class: "register_button" %>
</div>

appetizr/app/views/users/mis_restaurantes.html.erb
<div class="title_container categories_title_container">
  <h1 class="title">Mis <span class="title_key_word">Restaurantes</span></h1>
  <%= link_to new_restaurant_path, class: "categories_new_button" do %>
    <div>Añadir</div>
  <% end %>
</div>
<ul class="categories_list">
  <% @restaurants.each do |restaurant| %>
    <li>
      <%= link_to restaurant_path(restaurant) do %>
        <div class="category_box">
          <% if restaurant.ruta_img_fondo.present? %>
            <%= image_tag restaurant.ruta_img_fondo, class: "category_image" %>
          <% else %>
            <%= image_tag "/images/Default-restaurant-img.jpg", class: "category_image" %>
          <% end %>
          <div class="category_name"><%= restaurant.nombre %></div>
        </div>
      <% end %>
    </li>
  <% end %>
</ul>

appetizr/app/views/users/new.html.erb
<div class="log_in_container">
  <h1 class="log_in_title">DESCUBRE LA COMUNIDAD DE APPETIZR</h1>
  <%= form_with(model: @user, url: new_user_path, local: true, html: {style: "row-gap: 20px;"}) do |form| %>
    <div class="log_in_text_field_wrapper">
      <%= image_tag "/images/login-username.svg", class: "log_in_text_field_icon" %>
      <%= form.text_field :nombre, placeholder: "NOMBRE DE USUARIO", class: "log_in_text_field_field" %>
    </div>
    <div class="log_in_text_field_wrapper">
      <%= image_tag "/images/login-password.svg", class: "log_in_text_field_icon" %>
      <%= form.password_field :password, placeholder: "CONTRASEÑA", class: "log_in_text_field_field" %>
    </div>
    <div class="log_in_text_field_wrapper">
      <%= image_tag "/images/login-password.svg", class: "log_in_text_field_icon" %>
      <%= form.password_field :password_confirmation, placeholder: "CONFIRMAR CONTRASEÑA", class: "log_in_text_field_field" %>
    </div>
    <div>
      <%= form.submit "CREAR CUENTA", class: "register_button" %>
    </div>
  <% end %>
</div>

appetizr/app/views/users/show.html.erb
<div class="title_container" style="flex-direction: row !important">
    <h1 class="title">Mi <span class="title_key_word">Cuenta</span></h1>
    <% if @user.esAdmin %>
        <%= link_to "/admin", class: "admin_view_button", style: "text-decoration: none" do %>
            <div>Administración</div>
        <% end %>
    <% end %>
    <%= link_to logout_path, class: "logout_button", method: :delete do %>
        <div>Cerrar sesión</div>
    <% end %>
</div>

<%= form_with model: @user  do |form| %>
    <div class="my_account_form_container">
        <div class="my_account_user_passwd">
            <div>
                <%= form.label :password, "Modificar contraseña", class: "my_account_form_label", style: "padding-left: 10px" %>
            <br>
                <%= form.password_field :password, class: "my_account_form_text_field" %>
            </div>
            <% @user.errors.full_messages.each do |msg| %>
                <div><%= msg %></div>
            <% end %>
        </div>
        
        <div class="my_account_stats_container_wrapper">
            <div class="my_account_stats_container">
                <p class="my_account_stats_title">Estadísticas de tu cuenta</p>
                <div>
                    <div class="my_account_stats_line"><p>Posts</p><span class="my_account_metrics"><%= @num_posts %></span></div>
                    <div class="my_account_stats_line"><p>Reviews</p><span class="my_account_metrics"><%= @num_reviews %></span></div>
                    <div class="my_account_stats_line"><p>Respuestas</p><span class="my_account_metrics"><%= @num_responses %></span></div>
                    <div class="my_account_stats_line"><p id="my_account_month_comments">Comentarios del último mes</p><span class="my_account_metrics"><%= @num_comments_last_month %></span></div>
                </div>
            </div>
            <% if @num_restaurants_user > 0 %>
                <div class="my_account_stats_container">
                    <p class="my_account_stats_title">Estadísticas de tus restaurantes en el último mes</p>
                    <div>
                        <div class="my_account_stats_line"><p>Reviews en tus restaurantes</p><span class="my_account_metrics"><%= @num_reviews_restaurant_last_month %></span></div>
                        <div class="my_account_stats_line"><p>Reviews en tus platos</p><span class="my_account_metrics"><%= @num_reviews_dishes_last_month %></span></div>
                        <div class="my_account_stats_line"><p>Respuestas recibidas</p><span class="my_account_metrics"><%= @num_responses_restaurant_last_month %></span></div>
                        <div class="my_account_stats_line"><p>Likes recibidos</p><span class="my_account_metrics"><%= @num_likes_restaurant_last_month %></span></div>
                        <div class="my_account_stats_line"><p id="my_account_month_comments">Dislikes recibidos</p><span class="my_account_metrics"><%= @num_dislikes_restaurant_last_month %></span></div>
                    </div>
                </div>
            <% end %>
        </div>
        <div class="my_account_profile_img_container">
            <div class="my_account_profile_img_title">Imagen de Perfil</div>
            <% if @user.ruta_img_perfil.present? %>
                <%= image_tag @user.ruta_img_perfil, class: "my_account_profile_img" %>
            <% else %>
                <%= image_tag "/images/default_profile_img.jpg", class: "my_account_profile_img" %>
            <% end %>
            <label class="new_post_image_upload_button">
                <%= form.file_field :ruta_img_perfil %>
                <%= image_tag "/images/image-icon.svg", class: "new_post_image_upload_icon" %>
                <div class="new_post_image_upload_text">Modificar</div>
            </label>
        </div>
        <%= form.button type: :submit, class: "new_post_submit", style: "grid-column: span 3;" do %>
            <%= image_tag "/images/save.png", class: "new_post_submit_icon" %>
            <div class="new_post_submit_text">Guardar</div>
        <% end %>
    </div>
<% end %>