appetizr/config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/"), categories for now, will be explore (restaurantes#index)
  root "restaurants#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :categories, param: :nombre
  
  resources :restaurants do
    post '/rank', to: 'ranks#create'
    resources :dishes, only: [:show, :new, :create, :edit, :update, :destroy]
  end

  get 'search', to: 'restaurants#search', as: 'search_restaurants'
  get '/restaurants/:id/stats', to: 'restaurants#stats'
  get '/restaurants/:id/edit_info', to: 'restaurants#edit_info'
  
  resources :posts, only: [:new, :create, :destroy] do
    get '/responses', to: 'post_responses#index' 
  end
  resources :reviews, only: [:new, :create, :destroy] do
    get '/responses', to: 'review_responses#index' 
  end
  
  get '/users/mis_restaurantes', to: 'users#mis_restaurantes'
  resources :users, param: :nombre
  post '/users/new', to: 'users#create'
  get '/is_rest_owner', to: 'users#is_restaurant_owner'
  
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout',  to: 'logins#destroy'

  resources :reactions, only: [:create, :update]
  resources :responses, only: [:new, :create, :destroy]
  
  get '/nearme', to: 'nearme#index', as: 'nearme'


  # Error pages
  get '/404', to: 'errors#not_found', via: :all
  get '/500', to: 'errors#internal_server_error', via: :all

  
  # /admin tiene que renderizar la vista admin/dashboard.html.erb
  get '/admin', to: 'admin#dashboard', as: 'admin_dashboard'
  get '/admin/promote', to: 'admin#promote', as: 'admin_promote'
  namespace :admin do
    get 'actualizar_datos', to: 'admin#actualizar_datos'
  end




  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  
  # root "posts#index"
  match '*unmatched', to: 'errors#not_found', via: :all
end

appetizr/app/models/dish.rb
class Dish < ApplicationRecord
  belongs_to :restaurant
  has_many :reviews, as: :reviewable, dependent: :destroy
  
  validates :nombre, presence: true
  
end

appetizr/app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  include QueriesConcern
  def show
    session[:review_referer] = nil
    @restaurant = Restaurant.find(params[:restaurant_id])
    alleged_dish = Dish.find_by(id: params[:id], restaurant_id: params[:restaurant_id])
    if alleged_dish
      @dish = alleged_dish
    else
      redirect_to request.referer
    end
    @reviews_reactions = get_comment_pack(@dish.reviews.find_each, 'reviews', 'Review', "AND reviewable_type='Dish' AND reviewable_id=#{@dish.id}")
    @reviews_user_reactions = get_user_reactions_pack('reviews', 'Review', session[:username], "AND reviewable_id=#{@dish.id} AND reviewable_type='Dish'")
  end

  def new
    @dish = Dish.new
    session[:dish_restaurant] = params[:restaurant_id]
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def create
    nombre_imagen = subir_imagen(params.require(:dish)[:ruta_img_plato])
    @dish = Dish.new(dish_params.merge(ruta_img_plato: nombre_imagen, restaurant_id: session[:dish_restaurant]))
    if @dish.save
      redirect_to restaurant_path(session[:dish_restaurant])
    else
      flash[:fails] = "El plato no ha sido creado" 
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @dish = Dish.find(params[:id])
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def update
    @dish = Dish.find(params[:id])
    if params.require(:dish)[:ruta_img_plato].present?
      nombre_imagen = subir_imagen(params.require(:dish)[:ruta_img_plato])
      update_params = dish_params.merge(ruta_img_plato: nombre_imagen)
    else
      update_params = dish_params
    end
    if @dish.update(update_params)
      flash[:dishes] = "El plato ha sido modificado" 
      redirect_to restaurant_path(@dish.restaurant_id)
    else
      flash[:fails] = "El plato no ha sido modificado" 
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @dish = Dish.find(params[:id])
    @dish.destroy
    redirect_to restaurant_path(@dish.restaurant_id)
  end

  private
  def dish_params
    params.require(:dish).permit(:nombre, :descripcion, :ruta_img_plato, :precio)
  end
end

appetizr/app/helpers/dishes_helper.rb
module DishesHelper
end

appetizr/app/views/dishes/_form.html.erb
<!-- Formulario para crear un nuevo plato: tiene que usar el modelo Dish y el modelo Restaurant -->
<%= form_for @dish, url: restaurant_dishes_path(params[:restaurant_id]), html: { multipart: true } do |form| %>
  <div class="categories_new_form_container">
      <div class="categories_new_name_container">
        <% if !@dish.imported_id %>
          <div>
            <label class="my_account_form_label">Nombre del plato</label><br>
            <%= form.text_field :nombre, class: "my_account_form_text_field", placeholder: "Mi plato" %>
          </div>
        <% end %>

        <div>
          <label class="my_account_form_label">Descripción</label><br>
          <%= form.text_field :descripcion, class: "my_account_form_text_field", placeholder: "El mejor plato que vas a probar" %>
        </div>

        <div>
          <label class="my_account_form_label">Precio</label><br>
          <!-- El precio tiene que poder ser un numero decimal por lo que se usa el tipo number_field y para que pueda introducir un numero decimal se usa el atributo step -->
          <%= form.number_field :precio, class: "my_account_form_text_field", placeholder: "9.99", step: "0.01" %>
        </div>
      </div>

      <div class="my_account_profile_img_container">
        <div class="my_account_profile_img_title">Añade una imagen del plato</div>
        <% if @dish.ruta_img_plato.present? %>
          <%= image_tag "/images/"+@dish.ruta_img_plato, class: "categories_new_img", id: "restaurant_image" %>
        <% else %>
          <%= image_tag "/images/default-dish-img.jpg", class: "categories_new_img", id: "restaurant_image" %>
        <% end %>
        <label class="new_post_image_upload_button">
          <%= form.file_field :ruta_img_plato, id: "upload_image_input", style: "display:none;" %>
          <%= image_tag "/images/image-icon.svg", class: "new_post_image_upload_icon", onclick: "$('#upload_image_input').click();" %>
          <div class="new_post_image_upload_text">Modificar</div>
        </label>
      </div>

      <div class="categories_new_button_container">
        <%= form.button type: :submit, class: "new_post_submit" do %>
          <%= image_tag "/images/send.svg", class: "new_post_submit_icon" %>
          <div class="new_post_submit_text">Publicar</div>
        <% end %>
      </div>
  </div>
<% end %>



<script>
  document.getElementById('upload_image_input').addEventListener('change', function(event) {
    var reader = new FileReader();
    reader.onload = function(e) {
      document.getElementById('restaurant_image').src = e.target.result;
    };
    reader.readAsDataURL(event.target.files[0]);
  });
</script>

appetizr/app/views/dishes/edit.html.erb
<div class="title_container">
    <h1 class="title">Edita tu <span class="title_key_word">plato</span></h1>
</div>
<% if flash[:fails] %>
  <div class="notice" ><%= flash[:fails] %></div>
<% end %>
<%= render "form", dish: @dish %>

<% if !@dish.imported_id %> 
  <%= link_to restaurant_dish_path(@restaurant.id, @dish.id), style: "text-decoration: none; display: flex; justify-content: center;", data: {turbo_method: :delete} do %>
    <div class="restaurants_header_edit_button" style="width: 700px; background-color: var(--delete-color);">
      <span class="restaurants_header_edit_button_text" style="color: var(--black);">Eliminar Plato</span>
    </div> 
  <% end %>
<% end %>

appetizr/app/views/dishes/new.html.erb
<div class="title_container">
    <h1 class="title">Nuevo <span class="title_key_word">plato</span></h1>
</div>
<% if flash[:fails] %>
  <div class="notice" ><%= flash[:fails] %></div>
<% end %>
<%= render "form", dish: @dish %>

appetizr/app/views/dishes/show.html.erb
<div class="posts_container">
  <div class="title_container" style="flex-direction: row;">
    <div>
      <div class="title">Restaurante <span class="title_key_word"><%= @dish.restaurant.nombre %></span></div>
      <div class="subtitle">Comentarios sobre el plato:</div>
    </div>
    <!-- Mostrar el botón de editar solo si el usuario es el propietario del restaurante -->
    <% if session[:username].present? and user_is_owner?(@restaurant.id) %>
      <!-- Si el restaurante tiene su imported_id distinto de nil, significa que es un restaurante importado y no se puede editar -->
      <% if @dish.imported_id %>
        <%= link_to "#{ENV['EINA_EATS_WEB']}/platosrestaurante/#{@restaurant.imported_id}", style: "text-decoration: none" do %>
          <div class="restaurants_header_edit_button">
            <span class="restaurants_header_edit_button_text">Editar en EinaEats</span>
          </div> 
        <% end %>
      <% else %>
        <%= link_to edit_restaurant_dish_path(@restaurant.id), style: "text-decoration: none" do %>
          <div class="restaurants_header_edit_button">
            <span class="restaurants_header_edit_button_text">Editar</span>
          </div> 
        <% end %>
      <% end %>
    <% end %>
  </div>
  <div class="restaurant_dish_container">
    <% if @dish.ruta_img_plato.present? %>
      <%= image_tag "/images/"+@dish.ruta_img_plato, class: "restaurant_dish_img" %>
    <% else %>
      <%= image_tag "/images/default-dish-img.jpg", class: "restaurant_dish_img" %>
    <% end %>

    <div class="restaurant_dish_content">
      <div class="restaurant_dish_name" style="color: var(--black) !important;"><%= @dish.nombre%></div>
      <div class="restaurant_dish_desc" style="color: var(--black) !important;"><%= @dish.descripcion %></div>
    </div>

    <div style="display: flex; gap: 20px; align-items: center;">
      <div class="restaurant_dish_price" style="color: var(--black) !important;"><%= @dish.precio %> €</div>
    </div>
  </div>
  
  <div class="category_post_list" style="margin-top: 0;">
    <%= render "layouts/comment", comments: @dish.reviews, locals: {reactions: @reviews_reactions, user_reactions: @reviews_user_reactions}%>
  </div>
  <%= render "layouts/add_comment", path_param: new_review_path(review_to: @dish.id, review_type: "Dish") %>
</div>