appetizr/config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/"), categories for now, will be explore (restaurantes#index)
  root "restaurants#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :categories, param: :nombre
  
  resources :restaurants do
    post '/rank', to: 'ranks#create'
    resources :dishes, only: [:show, :new, :create, :edit, :update, :destroy]
  end

  get 'search', to: 'restaurants#search', as: 'search_restaurants'
  get '/restaurants/:id/stats', to: 'restaurants#stats'
  get '/restaurants/:id/edit_info', to: 'restaurants#edit_info'
  
  resources :posts, only: [:new, :create, :destroy] do
    get '/responses', to: 'post_responses#index' 
  end
  resources :reviews, only: [:new, :create, :destroy] do
    get '/responses', to: 'review_responses#index' 
  end
  
  get '/users/mis_restaurantes', to: 'users#mis_restaurantes'
  resources :users, param: :nombre
  post '/users/new', to: 'users#create'
  get '/is_rest_owner', to: 'users#is_restaurant_owner'
  
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout',  to: 'logins#destroy'

  resources :reactions, only: [:create, :update]
  resources :responses, only: [:new, :create, :destroy]
  
  get '/nearme', to: 'nearme#index', as: 'nearme'


  # Error pages
  get '/404', to: 'errors#not_found', via: :all
  get '/500', to: 'errors#internal_server_error', via: :all

  
  # /admin tiene que renderizar la vista admin/dashboard.html.erb
  get '/admin', to: 'admin#dashboard', as: 'admin_dashboard'
  get '/admin/promote', to: 'admin#promote', as: 'admin_promote'
  namespace :admin do
    get 'actualizar_datos', to: 'admin#actualizar_datos'
  end




  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  
  # root "posts#index"
  match '*unmatched', to: 'errors#not_found', via: :all
end

appetizr/app/models/appetizr_db_model.rb
class AppetizrDbModel < ApplicationRecord
  self.abstract_class = true
  establish_connection :default
end

appetizr/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

appetizr/app/models/category.rb
class Category < ApplicationRecord
  self.primary_key = "nombre"
  
  has_many :restaurants, class_name: 'Restaurant', foreign_key: 'categoria', dependent: :nullify
  has_many :posts, class_name: 'Post', foreign_key: 'categoria', dependent: :destroy
  validates :nombre, presence: true
end

appetizr/app/models/dish.rb
class Dish < ApplicationRecord
  belongs_to :restaurant
  has_many :reviews, as: :reviewable, dependent: :destroy
  
  validates :nombre, presence: true
  
end

appetizr/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category, class_name: 'Category', optional: true
  belongs_to :user, class_name: 'User', optional: true 
  belongs_to :restaurant, class_name: 'Restaurant', optional: true
  has_many :reactions, as: :reactionable, dependent: :delete_all
  has_many :responses, as: :respondable, dependent: :destroy

  before_destroy do |ts|
    responses.destroy
    reactions.delete
  end
end

appetizr/app/models/rank.rb
class Rank < ApplicationRecord
  belongs_to :user, class_name: 'User', optional: true
  belongs_to :restaurant, class_name: 'Restaurant', optional: true
  validates :who, uniqueness: {scope: :what}
end

appetizr/app/models/reaction.rb
class Reaction < ApplicationRecord
  validates :who, uniqueness: {scope: [:reactionable_id, :reactionable_type]}
  belongs_to :user, class_name: 'User', optional: true 
  belongs_to :reactionable, polymorphic: true
end

appetizr/app/models/response.rb
class Response < ApplicationRecord
  belongs_to :user, class_name: 'User', optional: true
  belongs_to :respondable, polymorphic: true
  has_many :reactions, as: :reactionable

  before_destroy do |ts|
    reactions.delete
  end
end

appetizr/app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :category, class_name: 'Category', optional: true
  has_many :ranks, class_name: 'Rank', foreign_key: 'what', dependent: :delete_all
  has_many :posts, class_name: 'Post', foreign_key: 'restaurant_id', dependent: :destroy
  has_many :reviews, as: :reviewable, dependent: :destroy
  has_many :dishes, dependent: :destroy
  has_and_belongs_to_many :users
  # ...
end

appetizr/app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user, class_name: 'User', optional: true
  belongs_to :reviewable, polymorphic: true
  has_many :responses, as: :respondable, dependent: :destroy
  has_many :reactions, as: :reactionable, dependent: :delete_all

  before_destroy do |ts|
    responses.destroy
    reactions.delete
  end
end

appetizr/app/models/user.rb
class User < ApplicationRecord
  self.primary_key = "nombre"

  has_many :posts, class_name: 'Post', foreign_key: 'autor', dependent: :destroy
  has_many :responses, class_name: 'Response', foreign_key: 'autor', dependent: :destroy
  has_many :reviews, class_name: 'Review', foreign_key: 'autor', dependent: :destroy
  has_many :ranks, class_name: 'Rank', foreign_key: 'who', dependent: :delete_all
  has_many :reactions, class_name: 'Reaction', foreign_key: 'who', dependent: :delete_all
  has_and_belongs_to_many :restaurants
  has_secure_password 


  before_destroy do |ts|
    responses.destroy
    reactions.delete
  end
end

appetizr/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  include QueriesConcern
  def index 
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:nombre])
    @category_posts = @category.posts.find_each
    @posts_reactions = get_comment_pack(@category_posts, 'posts', 'Post', "AND categoria='#{params[:nombre]}'")
    @comments_user_reactions = get_user_reactions_pack('posts', 'Post', session[:username], "AND categoria='#{params[:nombre]}'")
        #  for every comment, check whether a user has already reacted to that comment
    session[:post_category] = params[:nombre]
  end

  def new
    @category = Category.new
  end

  def create
    nombre_imagen = subir_imagen(params.require(:category)[:ruta_img])
    @category = Category.new(nombre: params[:category][:nombre], ruta_img: nombre_imagen)

    if @category.save
      redirect_to @category
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @category = Category.find(params[:nombre])
  end

  def update
    @category = Category.find(params[:nombre])
    nombre_imagen = subir_imagen(params.require(:category)[:ruta_img])
    if @category.update(category_params.merge(ruta_img: nombre_imagen))
      redirect_to @category
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy 
    @category = Category.find(params[:nombre])
    @category.destroy

    redirect_to root_path, status: :see_other
  end

  private 
    def category_params
      params.require(:category).permit(:nombre, :ruta_img)
    end
end

appetizr/app/helpers/categories_helper.rb
module CategoriesHelper
end

appetizr/app/helpers/dishes_helper.rb
module DishesHelper
end

appetizr/app/helpers/errors_helper.rb
module ErrorsHelper
end

appetizr/app/helpers/logins_helper.rb
module LoginsHelper
    def log_in(user)
        session[:username] = user.nombre
        session[:esAdmin] = user.esAdmin
      end
    
      def current_user
        if session[:username]
          @current_user ||= User.find_by(nombre: session[:username])
        end
      end
    
      def logged_in?
        !current_user.nil?
      end

      def admin?
        session[:esAdmin]
      end
    
      def log_out
        session.delete(:username)
        @current_user = nil
      end
    
      def current_user?(user)
        user == current_user
      end
    
      def redirect_back_or(default)
        redirect_to(session[:forwarding_url] || default)
        session.delete(:forwarding_url)
      end
    
      def store_location
        session[:forwarding_url] = request.original_url if request.get?
      end
end

appetizr/app/helpers/platos_helper.rb
module PlatosHelper
end

appetizr/app/helpers/posts_helper.rb
module PostsHelper
    def get_restaurant_of_post(post)
        if post.restaurant_id
            return Restaurant.find(post.restaurant_id)
        else
            return nil
        end
    end
end

appetizr/app/helpers/ranks_helper.rb
module RanksHelper
end

appetizr/app/helpers/reactions_helper.rb
module ReactionsHelper
end

appetizr/app/helpers/responses_helper.rb
module ResponsesHelper
end

appetizr/app/helpers/reviews_helper.rb
module ReviewsHelper
end

appetizr/app/helpers/users_helper.rb
module UsersHelper
end

appetizr/app/views/categories/_form.html.erb
<%= form_with model: @category do |form| %>
  <div class="categories_new_form_container">
      <div class="categories_new_name_container">
        <div>
          <label class="my_account_form_label">Nombre de la categoría</label><br>
          <%= form.text_field :nombre, class: "my_account_form_text_field", placeholder: "Burger" %>
        </div>
      </div>
      <div class="my_account_profile_img_container">
        <div class="my_account_profile_img_title">Añade una imagen identificativa</div>
        <% if @category.ruta_img.present? %>
            <%= image_tag "/images/"+@category.ruta_img, class: "categories_new_img" %>
        <% else %>
            <%= image_tag "/images/burger-category.png", class: "categories_new_img" %>
        <% end %>
        <label class="new_post_image_upload_button">
            <%= form.file_field :ruta_img %>
            <%= image_tag "/images/image-icon.svg", class: "new_post_image_upload_icon" %>
            <div class="new_post_image_upload_text">Modificar</div>
        </label>
      </div>

      <div class="categories_new_button_container">
        <%= form.button type: :submit, class: "new_post_submit" do %>
          <%= image_tag "/images/send.svg", class: "new_post_submit_icon" %>
          <div class="new_post_submit_text">Publicar</div>
        <% end %>
      </div>
  </div>
<% end %>

appetizr/app/views/categories/edit.html.erb
<div class="title_container">
    <h1 class="title">Editar <span class="title_key_word">categoría</span></h1>
</div>
<%= render "form", category: @category %>

<%= link_to category_path(@category.nombre), style: "text-decoration: none; display: flex; justify-content: center;", data: {turbo_method: :delete} do %>
    <div class="restaurants_header_edit_button" style="width: 700px; background-color: var(--delete-color);">
        <span class="restaurants_header_edit_button_text" style="color: var(--black);">Eliminar Categoría</span>
    </div> 
<% end %>

appetizr/app/views/categories/index.html.erb
<div class="title_container categories_title_container">
  <h1 class="title"><span class="title_key_word">Categorías</span> de conversación</h1>
  <% if session[:username].present? and getCurrentUser.esAdmin %>
    <%= link_to new_category_path, class: "categories_new_button" do %>
      <div>Añadir</div>
    <% end %>
  <% end %>
</div>
<ul class="categories_list">
  <% @categories.each do |category| %>
    <li>
      <%= link_to category_path(category) do %>
        <div class="category_box">
          <% if category.ruta_img.present? %>
            <%= image_tag "/images/"+category.ruta_img, class: "category_image" %>
          <% else %>
            <%= image_tag "/images/burger-category.png", class: "category_image" %>
          <% end %>
          <div class="category_name"><%= category.nombre %></div>
        </div>
      <% end %>
    </li>
  <% end %>
</ul>

appetizr/app/views/categories/new.html.erb
<div class="title_container">
    <h1 class="title">Nueva <span class="title_key_word">categoría</span></h1>
</div>
<%= render "form", category: @category %>

appetizr/app/views/categories/show.html.erb
<div class="posts_container">
  <div class="title_container categories_title_container">
    <h1 class="title"><span class="title_key_word"><%= @category.nombre %></span> en Zaragoza</h1>
    <% if session[:username].present? and getCurrentUser.esAdmin %>
      <div class="edit_delete_category_buttons">
        <%= link_to edit_category_path, class: "categories_new_button" do %>
          <div>Editar</div>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="category_post_list">
    <%= render "layouts/comment", comments: @category_posts, locals: {reactions: @posts_reactions, user_reactions: @comments_user_reactions} %>
  </div>
  <%= render "layouts/add_comment", path_param: new_post_path %>
</div>