appetizr/config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/"), categories for now, will be explore (restaurantes#index)
  root "restaurants#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :categories, param: :nombre
  
  resources :restaurants do
    post '/rank', to: 'ranks#create'
    resources :dishes, only: [:show, :new, :create, :edit, :update, :destroy]
  end

  get 'search', to: 'restaurants#search', as: 'search_restaurants'
  get '/restaurants/:id/stats', to: 'restaurants#stats'
  get '/restaurants/:id/edit_info', to: 'restaurants#edit_info'
  
  resources :posts, only: [:new, :create, :destroy] do
    get '/responses', to: 'post_responses#index' 
  end
  resources :reviews, only: [:new, :create, :destroy] do
    get '/responses', to: 'review_responses#index' 
  end
  
  get '/users/mis_restaurantes', to: 'users#mis_restaurantes'
  resources :users, param: :nombre
  post '/users/new', to: 'users#create'
  get '/is_rest_owner', to: 'users#is_restaurant_owner'
  
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout',  to: 'logins#destroy'

  resources :reactions, only: [:create, :update]
  resources :responses, only: [:new, :create, :destroy]
  
  get '/nearme', to: 'nearme#index', as: 'nearme'


  # Error pages
  get '/404', to: 'errors#not_found', via: :all
  get '/500', to: 'errors#internal_server_error', via: :all

  
  # /admin tiene que renderizar la vista admin/dashboard.html.erb
  get '/admin', to: 'admin#dashboard', as: 'admin_dashboard'
  get '/admin/promote', to: 'admin#promote', as: 'admin_promote'
  namespace :admin do
    get 'actualizar_datos', to: 'admin#actualizar_datos'
  end




  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  
  # root "posts#index"
  match '*unmatched', to: 'errors#not_found', via: :all
end

appetizr/app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :category, class_name: 'Category', optional: true
  has_many :ranks, class_name: 'Rank', foreign_key: 'what', dependent: :delete_all
  has_many :posts, class_name: 'Post', foreign_key: 'restaurant_id', dependent: :destroy
  has_many :reviews, as: :reviewable, dependent: :destroy
  has_many :dishes, dependent: :destroy
  has_and_belongs_to_many :users
  # ...
end

appetizr/app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
    include QueriesConcern
    def index
      @categories = Category.all
      @promoted_restaurant = Restaurant.find_by(id: Rails.application.config.promoted_restaurant)

      if params[:filter]
        @restaurants = Restaurant.where(categoria: params[:filter]) 
        session[:filter] = params[:filter]
      else
        @restaurants = Restaurant.all
        session[:filter] = nil
      end
      
      rats = Restaurant.joins(:ranks).select(:what, "AVG(valoracion) as rest_val").group(:what)
        # Si no hay valoraciones, se pone a 0
        if rats.empty?
          @ratings = nil
        else
          @ratings = rats
        end
      tops = Rank.select(:what, "AVG(valoracion) as total_valoracion").group(:what).order("total_valoracion DESC").limit(5)
      @tops = tops.map{|r| Restaurant.find(r.what)}.compact
    end

    def show
        @restaurant = Restaurant.find_by(id: params[:id])
        session[:post_category] = @restaurant.categoria
        if !@restaurant
          redirect_to "/not_found" 
          return
        end
        rats = Rank.select(:what, "AVG(valoracion) as rest_val").where(what: @restaurant.id).group(:what)
        # Si no hay valoraciones, se pone a 0
        if rats.empty?
          @ratings = nil
        else
          @ratings = rats[0].rest_val
        end
        @posts_reactions = get_comment_pack(@restaurant.posts.find_each, 'posts', 'Post', "AND restaurant_id=#{@restaurant.id}")
        @posts_user_reactions = get_user_reactions_pack('posts', 'Post', session[:username], "AND restaurant_id=#{@restaurant.id}")
        @reviews_reactions = get_comment_pack(@restaurant.reviews.find_each, 'reviews', 'Review', "AND reviewable_id=#{@restaurant.id} AND reviewable_type='Restaurant'")
        @reviews_user_reactions = get_user_reactions_pack('reviews', 'Review', session[:username], "AND reviewable_id=#{@restaurant.id} AND reviewable_type='Restaurant'")
    end

    def new
        @restaurant = Restaurant.new
    end

    def create
        nombre_imagen = subir_imagen(params.require(:restaurant)[:ruta_img_fondo])
        @restaurant = Restaurant.new(restaurant_params.merge(ruta_img_fondo: nombre_imagen))
        if @restaurant.save
            redirect_to @restaurant
          else
            render :new, status: :unprocessable_entity
          end
        @restaurant.users << User.find_by(nombre: session[:username])
    end

    def edit
        @restaurant = Restaurant.find(params[:id])
    end

    def update 
        @restaurant = Restaurant.find(params[:id])
        nombre_imagen = subir_imagen(params.require(:restaurant)[:ruta_img_fondo])
        if @restaurant.update(restaurant_params.merge(ruta_img_fondo: nombre_imagen))
            redirect_to @restaurant
          else
            render :new, status: :unprocessable_entity
          end
    end

    def destroy
        @restaurant = Restaurant.find(params[:id])
        @restaurant.destroy

        redirect_to root_path, status: :see_other
    end

    def search
        if params[:search]
            @restaurant= Restaurant.where("lower(nombre) LIKE ?", "%#{params[:search].downcase}%")

            #@restaurant = Restaurant.find_by(nombre: params[:search])
            if @restaurant
                redirect_to @restaurant[0]
            else 
                # flash.now[:notice] = "No se encontró ningún restaurante con ese nombre"
                redirect_to categories_path
            end
        else
            render :index
        end
    end

    def stats
      @restaurant = Restaurant.find(params[:id])
    end

    def edit_info
      @restaurant = Restaurant.find(params[:id])
    end

    private
    
    def restaurant_params
        params.require(:restaurant).permit(:categoria, :nombre, :ruta_img_fondo, :direccion, :telefono, :horario, :image)
    end
end

appetizr/app/helpers/restaurants_helper.rb
module RestaurantsHelper
  def get_rest_managers_posts(rest_id)
    results = ActiveRecord::Base.connection.execute("SELECT posts.* FROM posts, users, restaurants_users as ru WHERE ru.user_id=users.nombre AND ru.restaurant_id=#{rest_id} AND posts.autor=users.nombre AND posts.restaurant_id=#{rest_id}")
    vals = results.values.map{|post| Post.new(id: post[0], categoria: post[1], autor: post[2], contenido: post[3], ruta_img: post[4], created_at: post[5], updated_at: post[6], restaurant_id: post[7])}
    return vals
  end
  def get_total_reviews(rest)
    rest_revs = rest.reviews.length()
    acc_dish_revs = 0
    rest.dishes.each do |dish| 
      acc_dish_revs += dish.reviews.length()
    end
    rest_revs+acc_dish_revs
  end

  def user_is_owner?(rest_id)
    user_restos = ActiveRecord::Base.connection.execute("SELECT restaurants.id, restaurants.nombre 
                                                        FROM restaurants, users, restaurants_users as ru 
                                                        WHERE users.nombre='#{session[:username]}' 
                                                        AND users.nombre=ru.user_id 
                                                        AND ru.restaurant_id=restaurants.id ")
    rest_ids = user_restos.values.map { |rest| rest[0] }
    rest_ids.include?(rest_id)
  end
end

appetizr/app/views/restaurants/_form.html.erb
<%= form_with model: @restaurant, html: {multipart:true, remote: true} do |form| %>
  <div class="categories_new_form_container">
      <div class="categories_new_name_container">
        
        <% if !@restaurant.imported_id %>        
          <div>
            <label class="my_account_form_label">Nombre del restaurante</label><br>
            <%= form.text_field :nombre, class: "my_account_form_text_field", placeholder: "Mi restaurante" %>
          </div>

          <div>
            <label class="my_account_form_label">Teléfono de contacto</label><br>
            <%= form.number_field :telefono, class: "my_account_form_text_field", placeholder: "123456789", pattern: "[0-9]{9}" %>
          </div>
        <% end %>

        <div>
          <label class="my_account_form_label">Dirección</label><br>
          <%= form.text_field :direccion, class: "my_account_form_text_field", placeholder: "Calle Mayor, 8" %>
        </div>
        <div>
          <label class="my_account_form_label">Horario</label><br>
          <%= form.text_field :horario, class: "my_account_form_text_field", placeholder: "Todos los días de 20:00 a 0:00" %>
        </div>

        <div>
          <label class="my_account_form_label">Categoría</label><br>
            <%= form.collection_select :categoria, Category.all, :id, :nombre, { include_blank: "Seleccionar categoría" }, { class: "my_account_form_text_field" } %>
        </div>
      </div>
       
      <div class="my_account_profile_img_container">
        <div class="my_account_profile_img_title">Añade una imagen de fondo</div>
        <% if @restaurant.ruta_img_fondo.present? %>
          <%= image_tag @restaurant.ruta_img_fondo, class: "categories_new_img", id: "restaurant_image" %>
        <% else %>
          <%= image_tag "/images/Default-restaurant-img.jpg", class: "categories_new_img", id: "restaurant_image" %>
        <% end %>
        <label class="new_post_image_upload_button">
          <%= form.file_field :ruta_img_fondo, id: "upload_image_input", style: "display:none;" %>
          <%= image_tag "/images/image-icon.svg", class: "new_post_image_upload_icon", onclick: "$('#upload_image_input').click();" %>
          <div class="new_post_image_upload_text">Modificar</div>
        </label>
      </div>

      <div class="categories_new_button_container">
        <%= form.button type: :submit, class: "new_post_submit" do %>
          <%= image_tag "/images/send.svg", class: "new_post_submit_icon" %>
          <div class="new_post_submit_text">Publicar</div>
        <% end %>
      </div>
  </div>
<% end %>



<script>
  document.getElementById('upload_image_input').addEventListener('change', function(event) {
    var reader = new FileReader();
    reader.onload = function(e) {
      document.getElementById('restaurant_image').src = e.target.result;
    };
    reader.readAsDataURL(event.target.files[0]);
  });
</script>

appetizr/app/views/restaurants/_header.html.erb
<div class="restaurants_header">
  <div class="restaurants_img_container">
    <% if locals[:restaurant].ruta_img_fondo.present? %>
      <%= image_tag locals[:restaurant].ruta_img_fondo, class: "restaurants_img" %>
    <% else %>
      <%= image_tag "/images/Default-restaurant-img.jpg", class: "restaurants_img" %>
    <% end %>
  </div>
  <div class="restaurants_header_content">
    <div>
      <div class="title">
        <%= locals[:restaurant].nombre %> - <span class="title_key_word"><%= locals[:restaurant].categoria %></span>
      </div>
      <div class="restaurant_rating_container">
        <% if locals[:ratings] %>
          <% locals[:ratings].floor.times do %>
            <%= image_tag "/images/Star.svg", style: "width: 40px; height: 40px" %>
          <% end %>
          <div class="restaurant_rating_text"> - <span><%= sprintf('%.1f', locals[:ratings]) %></span></div>
        <% end %>
      </div>
    </div>
    
    <div class="restaurants_header_buttons_container">
      <div>
        <% if session[:username].present? and (user_is_owner?(locals[:restaurant].id) or soy_admin?) %>
          <!-- Si el restaurante tiene su imported_id distinto de nil, significa que es un restaurante importado y no se puede editar -->
          <div style=" display: flex; flex-direction: row; gap: 20px;">
            <% if locals[:restaurant].imported_id.nil? %>
              <%= link_to edit_restaurant_path(locals[:restaurant].id), style: "text-decoration: none;" do %>
                <div class="restaurants_header_edit_button">
                  <span class="restaurants_header_edit_button_text">Editar</span>
                </div>
              <% end %>
            <% else %>
              <% if soy_admin? %>
                <%= link_to edit_restaurant_path(locals[:restaurant].id), style: "text-decoration: none;" do %>
                  <div class="restaurants_header_edit_button">
                    <span class="restaurants_header_edit_button_text">Editar</span>
                  </div>
                <% end %>
              <% end %>
              <%= link_to Rails.application.config.EINAEATS_LOGIN , style: "text-decoration: none" do %>
                <div class="restaurants_header_edit_button">
                  <span class="restaurants_header_edit_button_text" style="text-align: center;">Editar en EinaEats</span>
                </div> 
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
    
      <% if locals[:restaurant].imported_id %>
        <%= link_to "#{Rails.application.config.EINAEATS_GO_TO_RESTAURANT}/#{locals[:restaurant].imported_id}" , style: "text-decoration: none" do %>
          <div class="restaurants_einaeats_button">
            <%= image_tag "/images/Bolsa-einaeats.svg" %>
            <span class="restaurant_einaeats_button_text">Pedir en EinaEats</span>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<div class="restaurants_header_botones">
    <a href="#restaurant_menu" class="restaurants_header_page_button">
      <div>Menú</div>
    </a>
    <a href="#restaurant_reviews" class="restaurants_header_page_button">
      <div>Reseñas</div>
    </a>
    <a href="#restaurant_posts" class="restaurants_header_page_button">
      <div>Posts del restaurante</div> 
    </a>
    <a href="#restaurant_info" class="restaurants_header_page_button">
      <div>Información</div>
    </a>
  </div>

appetizr/app/views/restaurants/edit.html.erb
<div class="title_container">
    <h1 class="title">Editar <span class="title_key_word">Restaurante</span></h1>
</div>
<%= render "form", restaurant: @restaurant %>
<% if @restaurant.imported_id %>
<% else %>
    <%= link_to restaurant_path(@restaurant.id), style: "text-decoration: none; display: flex; justify-content: center;", data: {turbo_method: :delete} do %>
        <div class="restaurants_header_edit_button" style="width: 700px; background-color: var(--delete-color);">
            <span class="restaurants_header_edit_button_text" style="color: var(--black);">Eliminar Restaurante</span>
        </div> 
    <% end %>
<% end %>

appetizr/app/views/restaurants/edit_info.html.erb
<div class="title_container">
    <h1 class="title">Mi <span class="title_key_word">Restaurante</span></h1>
    <%= link_to logout_path, class: "logout_button", method: :delete do %>
        <div>Log out</div>
    <% end %>
</div>


<%= form_with model: @restaurant, style: "background-color: var(--white)" do |form| %>
  <div class="my_account_form_container">
        <div class="my_account_user_passwd", style="grid-row: 1 / 2">
            <div style="padding-bottom: 10px;">
                <%= form.label :nombre, "Nombre del restaurante", class: "my_account_form_label" %>
            <br>
                <%= form.text_field :nombre, class: "my_account_form_text_field" %>
            </div>
            <div>
                <%= form.label :category, "Categoría", class: "my_account_form_label" %>
            <br>
                <%= collection_select(:nombre, :categoria, Category.all, :nombre, :nombre, {:selected => @restaurant.categoria}) %> 
            </div>
            <div>
                <%= form.label :profile_pic, "Foto de perfil" %>
                <%= image_tag @restaurant.profile_pic if @restaurant.profile_pic.attached? %>
                <br>
                <%= form.file_field :profile_pic %>
            </div>
            <div>
                <%= form.label :image, "Imagen de fondo del restaurante" %>
                <%= image_tag(@restaurant.image, width: "300px") if @restaurant.image.attached? %>
                <br>
                <%= form.file_field :image %>
            </div>
        </div>
        <div class="my_account_user_passwd" style="grid-column: 3">
            <div style="padding-bottom: 10px;">
                <%= form.label :direccion, "Dirección", class: "my_account_form_label" %>
            <br>
                <%= form.text_field :direccion, class: "my_account_form_text_field" %>
            </div>
            <div style="padding-bottom: 10px;">
                <%= form.label :telefono, "Contacto", class: "my_account_form_label" %>
            <br>
                <%= form.text_field :telefono, class: "my_account_form_text_field" %>
            </div>
            <div style="padding-bottom: 10px;">
                <%= form.label :horario, "Horario", class: "my_account_form_label" %>
            <br>
                <%= form.text_field :horario, class: "my_account_form_text_field" %>
            </div>
        </div>

        <% @restaurant.errors.full_messages.each do |msg| %>
            <div><%= msg %></div>
        <% end %>
    
        <div class="my_account_form_buttons">
            <%= form.submit "Guardar" %>
        </div>
  </div>
<% end %>

appetizr/app/views/restaurants/index.html.erb
<div class="explore_container">
    <div class="explore_best_valued">
        <div class="explore_top_section_title">Mejor valorados</div>
        <div class="explore_top_section_best_valued_list">
          <% @tops.each_with_index do |restaurant, pos| %>
            <%= link_to restaurant_path(restaurant), class: "explore_top_section_best_valued_list_item", style: "text-decoration: none" do %>
                <%= pos + 1 %> - <%= restaurant.nombre %> 
            <% end %>
          <% end %>
        </div>
    </div>
    <% if !@promoted_restaurant.nil? %>
    <div class="explore_promoted_restaurant">
        <div class="explore_top_section_title">Restaurante promocionado</div>
        <div class="explore_promoted_restaurant_box">
            <% if @promoted_restaurant.ruta_img_fondo.present? %>
                <%= image_tag "/images/"+@promoted_restaurant.ruta_img_fondo, class: "explore_promoted_restaurant_image" %>
            <% else %>
                <%= image_tag "/images/Default-restaurant-img.jpg", class: "explore_promoted_restaurant_image" %>
            <% end %>
            <div class="explore_promoted_restaurant_info">
                <div>
                    <div class="explore_promoted_restaurant_name">
                        <%= @promoted_restaurant.nombre %><br>
                        <span class="title_key_word"><%= @promoted_restaurant.categoria %></span>
                    </div>
                    <div class="explore_promoted_restaurant_stars">
                        <% if @ratings && !@ratings.select {|r| r.what == @promoted_restaurant.id}.empty? %>
                            <% @ratings.select {|r| r.what == @promoted_restaurant.id}[0][:rest_val].floor.times do %> 
                            <%= image_tag "/images/Star.svg", style: "width: 25px; height: 25px" %>
                        <% end %>
                        <% end %>
                    </div>
                </div>
                <div>
                <% if @promoted_restaurant.imported_id.present? %>
                    <%= link_to "#{Rails.application.config.EINAEATS_GO_TO_RESTAURANT}/#{@promoted_restaurant.imported_id}", class: "restaurants_einaeats_button" do %>
                        <%= image_tag "/images/Bolsa-einaeats.svg" %>
                        <span class="restaurant_einaeats_button_text">Pedir en EinaEats</span>
                    <% end %>
                <% end %>
                </div>
            </div>
        </div>
    </div>
    <% end %>
    <div class="explore_lower_section">
        <div class="explore_restaurants_filters">
            <div class="explore_restaurants_filters_title">Filtrar por categoría</div>
            
            <% if !session[:filter].present? %>
              <%= link_to restaurants_path, class: "explore_restaurants_filters_item", style: "background-color: var(--light-black); color: var(--strong-gold);" do %>
                <div>Todos los restaurantes</div>
              <% end %>
            <% else %>
              <%= link_to restaurants_path, class: "explore_restaurants_filters_item" do %>
                <div>Todos los restaurantes</div>
              <% end %>
            <% end %>
            <% @categories.each do |category| %>
              <% if session[:filter].present? and session[:filter] == category.nombre %>
                <%= link_to restaurants_path(filter: category.nombre), class: "explore_restaurants_filters_item", style: "background-color: var(--light-black); color: var(--strong-gold);" do %>
                    <div><%= category.nombre %></div>
                <% end %>
              <% else %>
                <%= link_to restaurants_path(filter: category.nombre), class: "explore_restaurants_filters_item" do %>
                    <div><%= category.nombre %></div>
                <% end %>
              <% end %>
            <% end %>
        </div>
        <div class="explore_restaurants_section">
            <% @restaurants.each do |restaurant| %>
                <%= link_to restaurant_path(restaurant), style: "text-decoration: none;" do %>
                    <div class="explore_restaurants_box">
                        <% if restaurant.ruta_img_fondo %>
                            <%= image_tag "/images/"+restaurant.ruta_img_fondo, class: "explore_restaurants_box_image" %>
                        <% else %>
                            <%= image_tag "/images/Default-restaurant-img.jpg", class: "explore_restaurants_box_image" %>
                        <% end %>
                        <div style="display: flex;flex-direction: column;justify-content: center;align-items: center;height: 100%;gap: 5px;">
                            <div class="explore_restaurant_box_name"><%= restaurant.nombre %></div>
                            <div class="explore_restaurant_box_category"><%= restaurant.categoria %></div>
                            <div>
                                <% if @ratings && !@ratings.select {|r| r.what == restaurant.id}.empty? %>
                                    <% @ratings.select {|r| r.what == restaurant.id}[0][:rest_val].floor.times do %> 
                                    <%= image_tag "/images/Star.svg", style: "width: 25px; height: 25px" %>
                                <% end %>
                                <% end %>
                            </div>
                        </div>
                    </div>
                <% end %>
            <% end %>
        </div>
    </div>
</div>

appetizr/app/views/restaurants/link_to_einaeats.html.erb
<div class="log_in_container">
  <h1 class="log_in_title">¿Qué tipo de cuenta quieres?</h1>
  <%= link_to 'Crear cuenta independiente', new_restaurant_path, class: "register_button" %> 
<div>
  <div>¿Tu restaurante está registrado en EinaEats?</div>
  <div>Haz que tu entrada tenga comentarios de platos y del restaurante</div>
  <%= link_to 'Enlazando las cuentas', "http://webdiis.unizar.es/~mena/", class: "register_button", target: :_blank %>
</div>
</div>

appetizr/app/views/restaurants/new.html.erb
<div class="title_container">
  <h1 class="title">Crea tu <span class="title_key_word">Restaurante</span></h1>
</div>
<%= render "form", restaurant: @restaurant %>

<div style="display: flex; justify-content: center;">
  <div class="restaurants_header_edit_button" style="width: 700px; margin-bottom: 20px;">
    <%= link_to Rails.application.config.EINAEATS_WEB+"/"+session[:username] , style: "text-decoration: none; ", target: :_blank do %>
      <span class="restaurants_header_edit_button_text">Vincular restaurante desde EinaEats</span>
    <% end %>
  </div> 
</div>

appetizr/app/views/restaurants/show.html.erb
<div>
  <%= render "header", locals: {restaurant: @restaurant, order: true, ratings: @ratings} %>

  <% if flash[:dishes] %>
    <div class="notice" ><%= flash[:dishes] %></div>
  <% end %>
  <div id="restaurant_menu" class="restaurant_section_title">Menú</div>
  <div class="restaurant_section_content" style="overflow: scroll;">
    <% @restaurant.dishes.each do |dish| %>
      <div class="restaurant_dish_container" onclick="window.location='<%= get_dish_path(dish) %>'" style="cursor: pointer;">
        <% if dish.ruta_img_plato.present? %>
          <%= image_tag "/images/"+dish.ruta_img_plato, class: "restaurant_dish_img" %>
        <% else %>
          <%= image_tag "/images/default-dish-img.jpg", class: "restaurant_dish_img" %>
        <% end %>

        <div class="restaurant_dish_content">
          <div class="restaurant_dish_name"><%= dish.nombre%></div>
          <div class="restaurant_dish_desc"><%= dish.descripcion %></div>
        </div>

        <div style="display: flex; gap: 20px; align-items: center;">
          <% if session[:username].present? and (user_is_owner?(@restaurant.id) or soy_admin?) %>
            <% if dish.imported_id %>
              <%= link_to "#{Rails.application.config.EINAEATS_WEB}/login", style: "text-decoration: none" do %>
                <div class="restaurants_new_dish_button">
                  <span class="restaurants_new_dish_button_text">Editar en EinaEats</span>
                </div> 
              <% end %>
            <% else %>
              <%= link_to edit_restaurant_dish_path(@restaurant.id, dish.id), style: "text-decoration: none", onclick: "event.stopPropagation();" do %>
                <div class="restaurants_new_dish_button">
                  <span class="restaurants_new_dish_button_text">Editar</span>
                </div> 
              <% end %>
            <% end %>
          <% end %>
          <div class="restaurant_dish_price"><%= dish.precio %> €</div>
        </div>
      </div>
    <% end %>

      <!--  Si el usuario es el propietario del restaurante mostar un botón con el enlace a la pagina de añadir plato -->
    <% if session[:username].present? and user_is_owner?(@restaurant.id) %>
      <div style="display: flex; flex-direction: column; align-items: center;">
        <%= link_to "Añadir plato", new_restaurant_dish_path(@restaurant.id), class: "restaurants_new_dish_button" %>
      </div>
    <% end %>
  </div>

  <div id="restaurant_reviews" class="restaurant_section_title"> Reseñas del restaurante </div>
  <div class="restaurant_section_content_comments">
    <div class="restaurant_section_content restaurant_section_content_comments">
      <div class="category_post_list">
        <%= render "layouts/comment", comments: @restaurant.reviews, locals: {reactions: @reviews_reactions, user_reactions: @reviews_user_reactions}%>
      </div>
      <%= render "layouts/add_comment", path_param: new_review_path(review_to: @restaurant.id, review_type: "Restaurant") %> 
    </div>
  </div>
  <div id="restaurant_posts" class="restaurant_section_title"> Posts del restaurante </div>
  <div class="restaurant_section_content restaurant_section_content_comments">
    <div class="category_post_list">
      <%= render "layouts/comment", comments: get_rest_managers_posts(@restaurant.id), locals: {reactions: @posts_reactions, user_reactions: @posts_user_reactions} %>
    </div>
    <% if session[:username].present? and user_is_owner?(@restaurant.id) %> 
      <%= render "layouts/add_comment", path_param: new_post_path(post_to: @restaurant.id, post_type: "Restaurant") %>
    <% end %>
  </div>

  <div id="restaurant_info" class="restaurant_section_title"> Información del restaurante </div>
  <div class="restaurant_section_content restaurant_section_content_info">
  <div class="restaurant_dir_tlf_container">
    <div class="restaurant_info_item">
      <div class="restaurant_info_subtitle"> Direccion </div>
      <%= @restaurant.direccion %>
    </div>
    <div class="restaurant_info_item">
      <div class="restaurant_info_subtitle"> Telefono </div>
      <%= @restaurant.telefono %>
    </div>
  </div>
  <div class="restaurant_dir_tlf_container">
    <div class="restaurant_info_item">
      <div class="restaurant_info_subtitle"> Horario </div>
      <%= @restaurant.horario %>
    </div>
  </div>
</div>

appetizr/app/views/restaurants/stats.html.erb
<div class="title">Estadísticas de <span class="title_key_word"><%= @restaurant.nombre %></span></div>

<h2>Comentarios sobre tí</h2>

<%= render "layouts/comment", comments: @restaurant.reviews %>

<div>
  Visitas a tu página web
  <span> 1000</span>
</div>
<div>
  Comentarios en tu página 
  <span> <%= get_total_reviews(@restaurant) %></span>
</div>